from torchvision import models
from torch import nn
from collections import OrderedDict


def convert_state_dict(state_dict):
    '''
    Function converts a torch model state_dict that is generated by a nn.DataParallel (multi GPU) scenario to a dict that is loadable by a single GPU / CPU scenario. Multi GPU dicts have the string 'module.' prepended to their keys. This function removes the substring 'module.' by removing the first 7 characters from the key.
    '''
    new_state_dict = OrderedDict()
    for key, value in state_dict.items():
        name = key[7:]
        new_state_dict[name] = value
    return new_state_dict


def get_model(model_arch, num_labels, pretrained=True):
    model = getattr(models, model_arch)(pretrained=pretrained, progress=True)
    model.fc = nn.Linear(model.fc.in_features, num_labels)
    return model
